"""Simplified game environment restrictions.

Mirrors the Lua mod that restricts Balatro to a smaller, more RL-friendly
state space.  Apply these restrictions on top of a normal run to get:

* Joker whitelist — only 14 simple scoring jokers appear in the shop
* Shop: jokers only — no vouchers, boosters, or consumables
* Fixed per-round resources — 8 hand cards, 4 hands, 4 discards
* Boss blinds disabled — no debuffs, no set-time penalties
* SkipBlind removed from legal actions — agent must always fight

Typical usage
-------------
After ``initialize_run``::

    gs = initialize_run(back_key, stake, seed)
    apply_to_run(gs)  # patches starting_params and marks gs["simplified"]

After each ``step`` that may have populated the shop::

    step(gs, action)
    if gs.get("phase") == GamePhase.SHOP:
        apply_to_shop(gs)

When computing legal actions::

    legal = filter_legal_actions(get_legal_actions(gs))
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

#: Joker center_keys allowed in the shop.
ALLOWED_JOKERS: frozenset[str] = frozenset(
    [
        "j_joker",
        "j_lusty_joker",
        "j_jolly",
        "j_droll",
        "j_crafty",
        "j_smeared",
        "j_zany",
        "j_mad",
        "j_sly",
        "j_wily",
        "j_abstract",
        "j_half",
        "j_scary_face",
        "j_greedy_joker",
    ]
)

HAND_SIZE: int = 8
HANDS_PER_ROUND: int = 4
DISCARDS_PER_ROUND: int = 4


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def apply_to_run(gs: dict[str, Any]) -> None:
    """Patch a freshly-initialized game state with simplified restrictions.

    Call this once after ``initialize_run``.  Sets the ``simplified`` flag
    in the game state so that ``game.py`` can disable boss blind effects
    at the point of blind selection.
    """
    sp = gs["starting_params"]
    sp["hand_size"] = HAND_SIZE
    sp["hands"] = HANDS_PER_ROUND
    sp["discards"] = DISCARDS_PER_ROUND

    # Propagate immediately to the live fields used by start_round
    gs["hand_size"] = HAND_SIZE
    rr = gs["round_resets"]
    rr["hands"] = HANDS_PER_ROUND
    rr["discards"] = DISCARDS_PER_ROUND

    # Flag consumed by game.py's _handle_select_blind to disable boss effects
    gs["simplified"] = True


def apply_to_shop(gs: dict[str, Any]) -> None:
    """Ensure the shop contains only allowed jokers, filling empty slots.

    Steps:
    1. Clear vouchers and boosters.
    2. Keep only cards already in the allowed-joker whitelist.
    3. Fill any remaining slots with random picks from ALLOWED_JOKERS,
       avoiding duplicates already present in the shop.

    Safe to call after every step when in SHOP phase — it is idempotent.
    Also handles rerolls (shop_cards is regenerated by ``_reroll_shop_cards``).
    """
    gs["shop_vouchers"] = []
    gs["shop_boosters"] = []

    shop_max: int = gs.get("shop", {}).get("joker_max", 2)
    kept = [c for c in gs.get("shop_cards", []) if _is_allowed_joker(c)]

    # Fill empty slots — avoid duplicating keys already in the shop
    rng = gs.get("rng")
    ante: int = gs.get("round_resets", {}).get("ante", 1)
    slot = 0
    while len(kept) < shop_max:
        used_keys = {getattr(c, "center_key", "") for c in kept}
        available = [k for k in _ALLOWED_JOKERS_SORTED if k not in used_keys]
        if not available:
            # All 14 jokers already present — allow duplicates as last resort
            available = _ALLOWED_JOKERS_SORTED
        key = _pick_joker_key(rng, ante, slot, available)
        card = _make_joker_card(key, gs, ante)
        if card is not None:
            kept.append(card)
        slot += 1
        if slot > shop_max * 3:
            break  # safety: avoid infinite loop if card creation keeps failing

    gs["shop_cards"] = kept


def filter_legal_actions(actions: list[Any]) -> list[Any]:
    """Remove ``SkipBlind`` from a legal-action list."""
    from jackdaw.engine.actions import SkipBlind

    return [a for a in actions if not isinstance(a, SkipBlind)]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

# Stable sorted list used for deterministic RNG picks
_ALLOWED_JOKERS_SORTED: list[str] = sorted(ALLOWED_JOKERS)


def _is_allowed_joker(card: Any) -> bool:
    """Return True if *card* is a joker in ALLOWED_JOKERS."""
    ability = getattr(card, "ability", {})
    if not isinstance(ability, dict):
        return False
    if ability.get("set") != "Joker":
        return False
    return getattr(card, "center_key", "") in ALLOWED_JOKERS


def _pick_joker_key(rng: Any, ante: int, slot: int, available: list[str]) -> str:
    """Pick a joker key from *available* using the game RNG for determinism."""
    if rng is not None:
        seed_val = rng.seed(f"simp_fill_{slot}_{ante}")
        key, _ = rng.element(available, seed_val)
        return key
    import random
    return random.choice(available)


def _make_joker_card(key: str, gs: dict[str, Any], ante: int) -> Any:
    """Create a shop-priced joker Card for *key*."""
    try:
        from jackdaw.engine.card import Card
        card = Card()
        card.set_ability(key)
        card.set_cost(
            inflation=gs.get("inflation", 0),
            discount_percent=gs.get("discount_percent", 0),
            ante=ante,
        )
        return card
    except Exception:
        return None
