"""Simplified game environment restrictions.

Mirrors the Lua mod that restricts Balatro to a smaller, more RL-friendly
state space.  Apply these restrictions on top of a normal run to get:

* Joker whitelist — only 14 simple scoring jokers appear in the shop
* Shop: jokers only — no vouchers, boosters, or consumables
* Fixed per-round resources — 8 hand cards, 4 hands, 4 discards
* Boss blinds disabled — no debuffs, no set-time penalties
* SkipBlind removed from legal actions — agent must always fight

Typical usage
-------------
After ``initialize_run``::

    gs = initialize_run(back_key, stake, seed)
    apply_to_run(gs)  # patches starting_params and marks gs["simplified"]

After each ``step`` that may have populated the shop::

    step(gs, action)
    if gs.get("phase") == GamePhase.SHOP:
        apply_to_shop(gs)

When computing legal actions::

    legal = filter_legal_actions(get_legal_actions(gs))
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

#: Joker center_keys allowed in the shop.
ALLOWED_JOKERS: frozenset[str] = frozenset(
    [
        "j_joker",
        "j_lusty_joker",
        "j_jolly",
        "j_droll",
        "j_crafty",
        "j_smeared",
        "j_zany",
        "j_mad",
        "j_sly",
        "j_wily",
        "j_abstract",
        "j_half",
        "j_scary_face",
        "j_greedy_joker",
    ]
)

HAND_SIZE: int = 8
HANDS_PER_ROUND: int = 4
DISCARDS_PER_ROUND: int = 4


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def apply_to_run(gs: dict[str, Any]) -> None:
    """Patch a freshly-initialized game state with simplified restrictions.

    Call this once after ``initialize_run``.  Sets the ``simplified`` flag
    in the game state so that ``game.py`` can disable boss blind effects
    at the point of blind selection.
    """
    sp = gs["starting_params"]
    sp["hand_size"] = HAND_SIZE
    sp["hands"] = HANDS_PER_ROUND
    sp["discards"] = DISCARDS_PER_ROUND

    # Propagate immediately to the live fields used by start_round
    gs["hand_size"] = HAND_SIZE
    rr = gs["round_resets"]
    rr["hands"] = HANDS_PER_ROUND
    rr["discards"] = DISCARDS_PER_ROUND

    # Flag consumed by game.py's _handle_select_blind to disable boss effects
    gs["simplified"] = True


def apply_to_shop(gs: dict[str, Any]) -> None:
    """Strip non-joker items from the shop and filter jokers to the whitelist.

    Safe to call after every step when in SHOP phase — it is idempotent.
    Also handles rerolls (shop_cards is regenerated by ``_reroll_shop_cards``).
    """
    gs["shop_vouchers"] = []
    gs["shop_boosters"] = []
    gs["shop_cards"] = [
        c for c in gs.get("shop_cards", []) if _is_allowed_joker(c)
    ]


def filter_legal_actions(actions: list[Any]) -> list[Any]:
    """Remove ``SkipBlind`` from a legal-action list."""
    from jackdaw.engine.actions import SkipBlind

    return [a for a in actions if not isinstance(a, SkipBlind)]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _is_allowed_joker(card: Any) -> bool:
    """Return True if *card* is a joker in ALLOWED_JOKERS."""
    ability = getattr(card, "ability", {})
    if not isinstance(ability, dict):
        return False
    if ability.get("set") != "Joker":
        return False
    return getattr(card, "center_key", "") in ALLOWED_JOKERS
